### ISSUE TITLE
播放器背景是透明的，请问是什么问题

### ISSUE THREAD

**Issue by sakurasep** [zDll233/Again#1]
### 截图：
![image](https://github.com/user-attachments/assets/8cff4211-1b90-4c58-b617-49e235f9ae09)
### 系统版本：
```
版本	Windows 10 专业版
版本号	22H2
安装日期	‎2024/‎11/‎11
操作系统内部版本	19045.5198
体验	Windows Feature Experience Pack 1000.19060.1000.0
```

**Comment by zDll233** [comment]
没有问题，因为是特地做成这样的🙃

**Comment by sakurasep** [comment]
因为看到readme里面，播放器有些许模糊效果，在我的电脑上并没有复现，当时在想是不是win10的问题
